//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <CONVERT>
 * f1 -> <L_PAREN>
 * f2 -> Argument()
 * f3 -> <R_PAREN>
 * f4 -> <USING>
 * f5 -> EncodingName()
 */
public class ConvertCall implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Argument f2;
   public NodeToken f3;
   public NodeToken f4;
   public EncodingName f5;

   public ConvertCall(NodeToken n0, NodeToken n1, Argument n2, NodeToken n3, NodeToken n4, EncodingName n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public ConvertCall(Argument n0, EncodingName n1) {
      f0 = new NodeToken("convert");
      f1 = new NodeToken("(");
      f2 = n0;
      f3 = new NodeToken(")");
      f4 = new NodeToken("using");
      f5 = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

