//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <EXISTS>
 * f1 -> Subquery()
 */
public class ExistsCall implements Node {
   public NodeToken f0;
   public Subquery f1;

   public ExistsCall(NodeToken n0, Subquery n1) {
      f0 = n0;
      f1 = n1;
   }

   public ExistsCall(Subquery n0) {
      f0 = new NodeToken("exists");
      f1 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

