//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <LIMIT>
 * f1 -> LimitOffset()
 * f2 -> [ <COMMA> LimitCount() ]
 */
public class LimitClause implements Node {
   public NodeToken f0;
   public LimitOffset f1;
   public NodeOptional f2;

   public LimitClause(NodeToken n0, LimitOffset n1, NodeOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public LimitClause(LimitOffset n0, NodeOptional n1) {
      f0 = new NodeToken("limit");
      f1 = n0;
      f2 = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

