//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ( <LEFT> | <RIGHT> )
 * f1 -> [ <OUTER> ]
 * f2 -> <JOIN>
 * f3 -> FromListExpression()
 */
public class OuterJoinSpec implements Node {
   public NodeChoice f0;
   public NodeOptional f1;
   public NodeToken f2;
   public FromListExpression f3;

   public OuterJoinSpec(NodeChoice n0, NodeOptional n1, NodeToken n2, FromListExpression n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public OuterJoinSpec(NodeChoice n0, NodeOptional n1, FromListExpression n2) {
      f0 = n0;
      f1 = n1;
      f2 = new NodeToken("join");
      f3 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

