//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <SELECT>
 * f1 -> [ <ALL> | <DISTINCT> ]
 * f2 -> ( <ASTERISK> | SelectList() )
 * f3 -> [ FromList() [ WhereClause() ] [ GroupByClause() ] [ OrderByClause() ] [ LimitClause() ] ]
 */
public class Query implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public NodeChoice f2;
   public NodeOptional f3;

   public Query(NodeToken n0, NodeOptional n1, NodeChoice n2, NodeOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public Query(NodeOptional n0, NodeChoice n1, NodeOptional n2) {
      f0 = new NodeToken("select");
      f1 = n0;
      f2 = n1;
      f3 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

