//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> WhenClauses()
 * f1 -> <ELSE>
 * f2 -> DefaultExpression()
 */
public class SearchedCaseExpression implements Node {
   public WhenClauses f0;
   public NodeToken f1;
   public DefaultExpression f2;

   public SearchedCaseExpression(WhenClauses n0, NodeToken n1, DefaultExpression n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public SearchedCaseExpression(WhenClauses n0, DefaultExpression n1) {
      f0 = n0;
      f1 = new NodeToken("else");
      f2 = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

