//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors with no argument must implement this interface.
 */

public interface GJNoArguVisitor<R> {

   //
   // GJ Auto class visitors with no argument
   //

   public R visit(NodeList n);
   public R visit(NodeListOptional n);
   public R visit(NodeOptional n);
   public R visit(NodeSequence n);
   public R visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( SqlStatement() )+
    * f1 -> <EOF>
    */
   public R visit(SqlScript n);

   /**
    * f0 -> SqlOperator()
    * f1 -> <SEMICOLON>
    */
   public R visit(SqlStatement n);

   /**
    * f0 -> Query()
    */
   public R visit(SqlOperator n);

   /**
    * f0 -> <SELECT>
    * f1 -> [ <ALL> | <DISTINCT> ]
    * f2 -> ( <ASTERISK> | SelectList() )
    * f3 -> [ FromList() [ WhereClause() ] [ GroupByClause() ] [ OrderByClause() ] [ LimitClause() ] ]
    */
   public R visit(Query n);

   /**
    * f0 -> SelectExpression()
    * f1 -> ( <COMMA> SelectExpression() )*
    */
   public R visit(SelectList n);

   /**
    * f0 -> ( RelationName() <PERIOD> <ASTERISK> | SchemaName() <PERIOD> RelationName() <PERIOD> <ASTERISK> | ValueExpression() [ [ <AS> ] Alias() ] )
    */
   public R visit(SelectExpression n);

   /**
    * f0 -> <FROM>
    * f1 -> FromListExpression()
    * f2 -> ( <COMMA> FromListExpression() )*
    */
   public R visit(FromList n);

   /**
    * f0 -> Relation()
    * f1 -> ( JoinClause() )*
    */
   public R visit(FromListExpression n);

   /**
    * f0 -> SingleRelation()
    *       | NamedSubquery()
    */
   public R visit(Relation n);

   /**
    * f0 -> Subquery()
    * f1 -> [ [ <AS> ] Alias() ]
    */
   public R visit(NamedSubquery n);

   /**
    * f0 -> <L_PAREN>
    * f1 -> Query()
    * f2 -> <R_PAREN>
    */
   public R visit(Subquery n);

   /**
    * f0 -> RelationSpec()
    * f1 -> [ [ <AS> ] Alias() ]
    */
   public R visit(SingleRelation n);

   /**
    * f0 -> [ SchemaName() <PERIOD> ]
    * f1 -> RelationName()
    */
   public R visit(RelationSpec n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(SchemaName n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(RelationName n);

   /**
    * f0 -> InnerJoinSpec() OnClause()
    *       | OuterJoinSpec() OnClause()
    *       | CrossJoinSpec()
    */
   public R visit(JoinClause n);

   /**
    * f0 -> [ <INNER> ]
    * f1 -> <JOIN>
    * f2 -> FromListExpression()
    */
   public R visit(InnerJoinSpec n);

   /**
    * f0 -> ( <LEFT> | <RIGHT> )
    * f1 -> [ <OUTER> ]
    * f2 -> <JOIN>
    * f3 -> FromListExpression()
    */
   public R visit(OuterJoinSpec n);

   /**
    * f0 -> <CROSS>
    * f1 -> <JOIN>
    * f2 -> FromListExpression()
    */
   public R visit(CrossJoinSpec n);

   /**
    * f0 -> <ON>
    * f1 -> SearchCondition()
    */
   public R visit(OnClause n);

   /**
    * f0 -> <WHERE>
    * f1 -> SearchCondition()
    */
   public R visit(WhereClause n);

   /**
    * f0 -> <HAVING>
    * f1 -> SearchCondition()
    */
   public R visit(HavingClause n);

   /**
    * f0 -> <GROUP>
    * f1 -> <BY>
    * f2 -> GroupByList()
    */
   public R visit(GroupByClause n);

   /**
    * f0 -> GroupByExpression()
    * f1 -> ( <COMMA> GroupByExpression() )*
    */
   public R visit(GroupByList n);

   /**
    * f0 -> ValueExpression()
    */
   public R visit(GroupByExpression n);

   /**
    * f0 -> <ORDER>
    * f1 -> <BY>
    * f2 -> OrderByList()
    */
   public R visit(OrderByClause n);

   /**
    * f0 -> OrderByExpression()
    * f1 -> ( <COMMA> OrderByExpression() )*
    */
   public R visit(OrderByList n);

   /**
    * f0 -> ValueExpression()
    * f1 -> [ <ASC> | <DESC> ]
    */
   public R visit(OrderByExpression n);

   /**
    * f0 -> <LIMIT>
    * f1 -> LimitOffset()
    * f2 -> [ <COMMA> LimitCount() ]
    */
   public R visit(LimitClause n);

   /**
    * f0 -> ValueExpression()
    */
   public R visit(LimitOffset n);

   /**
    * f0 -> ValueExpression()
    */
   public R visit(LimitCount n);

   /**
    * f0 -> BinaryOperator()
    *       | ParenthesizedExpression()
    */
   public R visit(ValueExpression n);

   /**
    * f0 -> OperandExpression()
    * f1 -> ( ArithmeticalOperator() | EqualityTest() | LogicalTest() | NullTest() | BetweenTest() )*
    */
   public R visit(BinaryOperator n);

   /**
    * f0 -> ( <PLUS> | <MINUS> | <ASTERISK> | <SLASH> | <PERCENT> | <DIV> | <MOD> )
    * f1 -> OperandExpression()
    */
   public R visit(ArithmeticalOperator n);

   /**
    * f0 -> ( <LT> | <GT> | <EQ> | <LTE> | <GTE> | <NE> )
    * f1 -> OperandExpression()
    */
   public R visit(EqualityTest n);

   /**
    * f0 -> ( <LIKE> | <AND> | <OR> | <XOR> )
    * f1 -> OperandExpression()
    */
   public R visit(LogicalTest n);

   /**
    * f0 -> <IS>
    * f1 -> [ <NOT> ]
    * f2 -> <NULL>
    */
   public R visit(NullTest n);

   /**
    * f0 -> <BETWEEN>
    * f1 -> OperandExpression()
    * f2 -> <AND>
    * f3 -> OperandExpression()
    */
   public R visit(BetweenTest n);

   /**
    * f0 -> <L_PAREN>
    * f1 -> ValueExpression()
    * f2 -> <R_PAREN>
    */
   public R visit(ParenthesizedExpression n);

   /**
    * f0 -> UnaryOperator()
    *       | UnaryOperand()
    */
   public R visit(OperandExpression n);

   /**
    * f0 -> ( <EXCLAMATION> | <NOT> | <TILDE> | <MINUS> )
    * f1 -> OperandExpression()
    */
   public R visit(UnaryOperator n);

   /**
    * f0 -> FunctionCall()
    *       | Subquery()
    *       | Literal()
    *       | ColumnExpression()
    */
   public R visit(UnaryOperand n);

   /**
    * f0 -> OrdinaryFunctionCall()
    *       | AggregateFunctionCall()
    *       | BuiltInFunctionCall()
    */
   public R visit(FunctionCall n);

   /**
    * f0 -> FunctionName()
    * f1 -> <L_PAREN>
    * f2 -> ArgList()
    * f3 -> <R_PAREN>
    */
   public R visit(OrdinaryFunctionCall n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(FunctionName n);

   /**
    * f0 -> Argument()
    * f1 -> ( <COMMA> Argument() )*
    */
   public R visit(ArgList n);

   /**
    * f0 -> ( <MIN> | <MAX> | <COUNT> | <AVG> | <SUM> | <AGGREGATE> FunctionName() )
    * f1 -> <L_PAREN>
    * f2 -> [ <ALL> | <DISTINCT> ]
    * f3 -> ( <ASTERISK> | Argument() )
    * f4 -> <R_PAREN>
    */
   public R visit(AggregateFunctionCall n);

   /**
    * f0 -> CastCall()
    *       | ConvertCall()
    *       | ExistsCall()
    *       | InCall()
    *       | CaseCall()
    */
   public R visit(BuiltInFunctionCall n);

   /**
    * f0 -> <CAST>
    * f1 -> <L_PAREN>
    * f2 -> Argument()
    * f3 -> <AS>
    * f4 -> Type()
    * f5 -> <R_PAREN>
    */
   public R visit(CastCall n);

   /**
    * f0 -> <CONVERT>
    * f1 -> <L_PAREN>
    * f2 -> Argument()
    * f3 -> <R_PAREN>
    * f4 -> <USING>
    * f5 -> EncodingName()
    */
   public R visit(ConvertCall n);

   /**
    * f0 -> <EXISTS>
    * f1 -> Subquery()
    */
   public R visit(ExistsCall n);

   /**
    * f0 -> <IN>
    * f1 -> ( Subquery() | <L_PAREN> ArgList() <R_PAREN> )
    */
   public R visit(InCall n);

   /**
    * f0 -> <CASE>
    * f1 -> ( SimpleCaseExpression() | SearchedCaseExpression() )
    * f2 -> <END>
    */
   public R visit(CaseCall n);

   /**
    * f0 -> ValueExpression()
    * f1 -> SearchedCaseExpression()
    */
   public R visit(SimpleCaseExpression n);

   /**
    * f0 -> WhenClauses()
    * f1 -> <ELSE>
    * f2 -> DefaultExpression()
    */
   public R visit(SearchedCaseExpression n);

   /**
    * f0 -> ( WhenClause() )+
    */
   public R visit(WhenClauses n);

   /**
    * f0 -> <WHEN>
    * f1 -> WhenTest()
    * f2 -> <THEN>
    * f3 -> WhenOptionExpression()
    */
   public R visit(WhenClause n);

   /**
    * f0 -> ValueExpression()
    */
   public R visit(WhenTest n);

   /**
    * f0 -> ValueExpression()
    */
   public R visit(WhenOptionExpression n);

   /**
    * f0 -> ValueExpression()
    */
   public R visit(DefaultExpression n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(EncodingName n);

   /**
    * f0 -> ValueExpression()
    */
   public R visit(Argument n);

   /**
    * f0 -> FullyQualifiedColumnName()
    *       | QualifiedColumnName()
    *       | UnqualifiedColumnName()
    */
   public R visit(ColumnExpression n);

   /**
    * f0 -> SchemaName()
    * f1 -> <PERIOD>
    * f2 -> RelationName()
    * f3 -> <PERIOD>
    * f4 -> ColumnName()
    */
   public R visit(FullyQualifiedColumnName n);

   /**
    * f0 -> RelationNameOrAlias()
    * f1 -> <PERIOD>
    * f2 -> ColumnName()
    */
   public R visit(QualifiedColumnName n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(RelationNameOrAlias n);

   /**
    * f0 -> ColumnName()
    */
   public R visit(UnqualifiedColumnName n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(ColumnName n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Alias n);

   /**
    * f0 -> ValueExpression()
    */
   public R visit(SearchCondition n);

   /**
    * f0 -> NumericOrStringLiteral()
    *       | BooleanLiteral()
    *       | NullLiteral()
    */
   public R visit(Literal n);

   /**
    * f0 -> <INTEGER_LITERAL>
    *       | <FLOATING_POINT_LITERAL>
    *       | <STRING_LITERAL>
    */
   public R visit(NumericOrStringLiteral n);

   /**
    * f0 -> <TRUE>
    *       | <FALSE>
    */
   public R visit(BooleanLiteral n);

   /**
    * f0 -> <NULL>
    */
   public R visit(NullLiteral n);

   /**
    * f0 -> NumericType()
    *       | StringType()
    *       | BooleanType()
    *       | DatetimeType()
    */
   public R visit(Type n);

   /**
    * f0 -> <TINYINT>
    *       | <SMALLINT>
    *       | <INT>
    *       | <INTEGER>
    *       | <BIGINT>
    */
   public R visit(NumericType n);

   /**
    * f0 -> <CHAR>
    *       | <VARCHAR>
    */
   public R visit(StringType n);

   /**
    * f0 -> <BOOLEAN>
    */
   public R visit(BooleanType n);

   /**
    * f0 -> <DATE>
    *       | <TIME>
    *       | <DATETIME>
    */
   public R visit(DatetimeType n);

}

